### ISSUE TITLE
Incorrect MIME type conversion when uploading MP3/WAV

### ISSUE THREAD

**Issue by adam-etan** [twilio-labs/serverless-api#22] opened 2019-12-05 20:48 UTC
Using serverless toolkit, when an asset of MP3 or WAV is uploaded, MIME type is converted to`application/octet-stream` which prevents twiml `<play>` from being able to play it.

**Before (localhost)**
![Screen Shot 2019-12-05 at 1 50 08 PM](https://user-images.githubusercontent.com/47754266/70277375-1fc07b80-1767-11ea-9bee-dfc301d165b7.png)

**After `twilio serverless:deploy`**
![after-upload](https://user-images.githubusercontent.com/47754266/70277430-3d8de080-1767-11ea-8662-a698e3b15122.png)

**Comment by dkundel** [comment] 2019-12-05 22:51
Hi @adam-etan 

I'm looking into this but so far I couldn't reproduce it. I downloaded the file at https://demo.twilio.com/docs/classic.mp3 and saved it into a project of my own.

Here's the output of the file command:
![Screen Shot of console showing output of audio/mpeg](https://user-images.githubusercontent.com/1505101/70280844-40d89a80-176e-11ea-871f-7ec766226652.png)

Once I run `twilio serverless:deploy` and run the same command I get `audio/mpeg`:
![Screen Shot of console showing output of audio/mpeg](https://user-images.githubusercontent.com/1505101/70280921-74b3c000-176e-11ea-9024-079df01cb43c.png)

You can test it by running: 
```bash
curl -s -o /dev/null -w '%{content_type}' 'https://repro-serverless-3350-dev.twil.io/classic.mp3'
```

The library is using under the hood [`file-type`](https://npm.im/file-type) to determine the file type of assets. Not sure why this is failing for your file

https://github.com/twilio-labs/serverless-api/blob/master/src/utils/content-type.ts#L19-L24

**Comment by adam-etan** [comment] 2019-12-05 23:07
@dkundel  Can you try [this](https://hold-8826-prcct372.twil.io/I15BXXBetweenMOH.mp3) one? It plays for us in the twilio console ui default assets, and locally but not when uploaded.

**Comment by dkundel** [comment] 2019-12-06 17:55
Okay good news is that I was able to reproduce it but it seems like the detection on the Serverless Toolkit side seems to be fine. You can see yourself by running `DEBUG=twilio-serverless-api:assets twilio serverless:deploy` and it should log which mime types were detected. I contacted the API team to see if something on their side is going wrong.

**Comment by dkundel** [comment] 2020-05-15 23:53
This should have been fixed by the API now since it will take content hints

**Closed by dkundel** 2020-05-15 23:53 UTC
